cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:book_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:book_id>/', views.cart_remove, name='cart_remove'),
]

catalog/urls.py
from django.urls import path
from catalog import views

app_name = 'catalog'

urlpatterns = [
    path('', views.home, name='home'),
    path('books/', views.books, name='books'),
    path('authors/', views.authors, name='authors'),
    # Lookup by id only, use slug only for SEO/readability
    path('book/<int:pk>', views.book_detail, name='book_detail'),
    path('book/<int:pk>/<slug:slug>', views.book_detail, name='book_detail'),
    path('author/<int:pk>', views.author_detail, name='author_detail'),
    path('author/<int:pk>/<slug:slug>', views.author_detail, name='author_detail')
]

digital_library/urls.py
from django.contrib import admin
from django.urls import path, include
# Develoment only
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('', include('catalog.urls', namespace='catalog')),
    path('orders/', include('orders.urls', namespace='orders'))
]


if settings.DEBUG: # new
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path

from . import views

app_name = 'orders'

urlpatterns = [
    path('create/', views.order_create, name='order_create'),
    path('', views.user_orders, name='user_orders'),
]

cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]

class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES,
                                      coerce=int)
    # the existing quantity has to be updated with the given quantity
    update = forms.BooleanField(required=False,
                                initial=False,
                                widget=forms.HiddenInput)

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from catalog.models import Book, BookInstance
from .cart import Cart
from .forms import CartAddProductForm


@require_POST
def cart_add(request, book_id):
    cart = Cart(request)
    #book_id = BookInstance.objects.get(id=book_id)
    #print(book_id)
    book = get_object_or_404(Book, id=book_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(book=book,
                 quantity=cd['quantity'],
                 update_quantity=cd['update'])
    return redirect('cart:cart_detail')

def cart_remove(request, book_id):
    cart = Cart(request)
    book = get_object_or_404(Book, id=book_id)
    cart.remove(book)
    return redirect('cart:cart_detail')

def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(initial={'quantity': item['quantity'],
                                                          'update': True})
    return render(request, 'cart/detail.html', {'cart': cart})

cart/templates/cart/detail.html
{% extends "catalog/home.html" %}
{% load widget_tweaks %}
{% load static %}
{% block content %}
<div class="col-lg-9">
<link href="//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">
{% if cart%}
<h1>Your shopping cart</h1>
{% for item in cart %}
{% with book=item.book %}
	<table id="cart" class="table table-hover table-condensed">
    				<thead>
						<tr>
							<th style="width:50%"></th>
							<th style="width:10%">Price</th>
                            <th style="width:8%">Quantity</th>
                            <th style="width:10%"></th>
							<th style="width:22%" class="text-center">Subtotal</th>							
						</tr>
					</thead>
					<tbody>
						<tr>
							<td data-th="Product">
								<div class="row">
									<div class="col-sm-3 hidden-xs"><a href="{{ book.get_absolute_url }}"><img src="{{ book.cover.url }}" class="img-responsive" height="100" width="80"/></a></div>
									<div class="col-sm-9">
										<h4 class="nomargin">{{ book }}</h4>
										<p>{{book.description|truncatewords:10}}</p>
									</div>
								</div>
							</td>
                            <td data-th="Price">${{ item.price }}</td>
                                <form action="{% url "cart:cart_add" book.id %}" method="post">
                                    <td data-th="Quantity">
                                        {{ item.update_quantity_form.quantity|add_class:"form-control text-center" }}								
                                    </td>
                                    <td class="actions" data-th="">
                                        {{ item.update_quantity_form.update }}
                                        <button class="btn btn-info btn-sm"><i class="fa fa-refresh"></i></button>																
                                        {% csrf_token %}                                                                            
                                    <a href="{% url "cart:cart_remove" book.id%}">Remove</a>                                    
                                </td>                                    
                                </form>
                            
                            </td>

							<td data-th="Subtotal" class="text-center">${{ item.total_price }}</td>

                        </tr>
                        {% endwith %}
                        {% endfor %}
					</tbody>
					<tfoot>					
						<tr>
							<td><a href="{% url "catalog:books" %}" class="btn btn-warning"><i class="fa fa-angle-left"></i> Continue Shopping</a></td>
							<td colspan="2" class="hidden-xs"></td>
							<td class="hidden-xs text-center"><strong>Total ${{ cart.get_total_price }}</strong></td>
							<td><a href="{% url "orders:order_create" %}" class="btn btn-success btn-block">Checkout <i class="fa fa-angle-right"></i></a></td>
						</tr>
					</tfoot>
				</table>
{% else %}
<h1>Your Shopping Cart is empty.</h1>
Your Shopping Cart lives to serve. Give it purpose — fill it with books. If you already have an account, Sign In to see your Cart.
Continue shopping on the <a href="{% url "catalog:books" %}">homepage</a> 
{% endif %}
{% endblock %}
</div>