cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:book_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:book_id>/', views.cart_remove, name='cart_remove'),
]

digital_library/urls.py
from django.contrib import admin
from django.urls import path, include
# Develoment only
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('', include('catalog.urls', namespace='catalog')),
    path('orders/', include('orders.urls', namespace='orders'))
]


if settings.DEBUG: # new
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path

from . import views

app_name = 'orders'

urlpatterns = [
    path('create/', views.order_create, name='order_create'),
    path('', views.user_orders, name='user_orders'),
]

orders/models.py
from django.db import models

from users.models import User
from catalog.models import Book


class Order(models.Model):
    """Model representing a customer detail information."""

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    braintree_id = models.CharField(max_length=150, blank=True)
    order_first_name = models.CharField(max_length=100)
    order_last_name = models.CharField(max_length=100)
    address = models.CharField(max_length=150)
    address2 = models.CharField(max_length=150, blank=True)
    postal_code = models.CharField(max_length=16)
    city = models.CharField(max_length=100)
    state = models.CharField(max_length=100)
    comment = models.CharField(max_length=250, blank=True)
    phone_number = models.CharField(max_length=12)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    paid = models.BooleanField(default=False)
    
    class Meta:
        ordering = ('-created',)
    
    def __str__(self):
        return 'Order {}'.format(self.id)
    
    def get_total_cost(self):
        """
        Get total cost for all the books in the order.
        OrderBook.objects.all()
        """
        return sum(book.get_cost() for book in self.books.all())

class OrderBook(models.Model):
    """Model allows to store the book and quantity with price."""

    order = models.ForeignKey(Order, related_name='books',
                              on_delete=models.CASCADE)
    book = models.ForeignKey(Book, related_name='order_book',
                             on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    quantity = models.PositiveIntegerField(default=1)

    def __str__(self):
        return '{}'.format(self.id)
   
    def get_cost(self):
        return self.price * self.quantity

orders/forms.py
from django import forms
from django.forms import TextInput
from .models import Order
from users.models import User


class OrderCreateForm(forms.ModelForm):
    """Customer order form."""
    class Meta:
        model = Order
        exclude = ["user"]
        fields = ['order_first_name', 'order_last_name',
                 'address', 'address2', 'postal_code', 'city',
                 'state', 'phone_number', 'comment']
        labels = {
            'order_first_name': 'First Name',
            'order_last_name': 'Last Name',
            'postal_code': 'Zip'
            }

orders/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.urls import reverse

from .models import OrderBook, Order
from .forms import OrderCreateForm
from cart.cart import Cart
from users.models import User
from .tasks import order_created


@login_required
def order_create(request):
    """Render the form and create a new order."""

    cart = Cart(request)
    # get logged user and declare the initial values
    user = User.objects.get(email=request.user)
    data = {'order_first_name': user.first_name,
            'order_last_name': user.last_name}
    if request.method == 'POST':
        form = OrderCreateForm(request.POST, initial=data)
        if form.is_valid():
            order = form.save(commit=False)
            order.user = user
            order = form.save()
            for book in cart:
                OrderBook.objects.create(order=order,
                                         book=book['book'],
                                         price=book['price'],
                                         quantity=book['quantity'])
            cart.clear()
            # launch asynchronous task
            order_created.delay(order.id, user.email)
            # set the order in the session
            request.session['order_id'] = order.id
            # redirect for payment
            return redirect(reverse('payment:process'))
    else:
        form = OrderCreateForm(initial=data)
    return render(request, 'orders/order/create.html',
                  {'cart':cart, 'form':form})

@login_required
def user_orders(request):
    """Render orders for the current user."""

    user_order = Order.objects.filter(user=User.objects.get(email=request.user))
    #user_order.order_set.all()
    return render(
                request,
                'orders/created.html',
                {
                    'user_order': user_order
                }
            )

orders/templates/orders/order/create.html
{% extends "catalog/home.html" %}
{% load widget_tweaks %}
{% block title %}
Checkout
{% endblock %}
{% block content %}
<div class="col-lg-9">
    <h1>Checkout</h1>
        <div class="order-info">
        <h3>Your order</h3>
            <ul>
            {% for item in cart %}
                <li>
                {{ item.quantity }}x {{ item.book.title }}
                <span>${{ item.total_price }}</span>
            </li>
            {% endfor %}
            </ul>
        <p>Total: ${{ cart.get_total_price }}</p>
        </div>   
    <form action="." method="post">
        {% csrf_token %}
        {{form.non_field_errors}}
        <div class="form-row">
        <div class="form-group col-md-6">
            <label for="{{form.order_first_name.name}}">{{form.order_first_name.label}}</label>
            {{form.order_first_name|add_class:'form-control'|attr:"placeholder:First Name"}}
            {{form.non_field_errors}}
        </div>
        <div class="form-group col-md-6">
            <label for="{{form.order_last_name.name}}">{{form.order_last_name.label}}</label>
            {{form.order_last_name|add_class:'form-control'|attr:"placeholder:Last Name"}}
            {{form.non_field_errors}}
        </div>
        </div>
        <div class="form-group">
                <label for="{{form.address.name}}">{{form.address.label}}</label>
                {{form.address|add_class:'form-control'|attr:"placeholder:1234 Main St"}}
                {{form.non_field_errors}}
        </div>
        <div class="form-group">
                <label for="{{form.address2.name}}">{{form.address2.label}}</label>
                {{form.address2|add_class:'form-control'|attr:"placeholder:Apartment, studio, or floor"}}
                {{form.non_field_errors}}
        <div class="form-row">
        <div class="form-group col-md-6">
                <label for="{{form.city.name}}">{{form.city.label}}</label>
                {{form.city|add_class:'form-control'}}
                {{form.non_field_errors}}
        </div>
        <div class="form-group col-md-4">
                <label for="{{form.state.name}}">{{form.state.label}}</label>
                {{form.state|add_class:'form-control'}}
                {{form.non_field_errors}}
            </select>
        </div>
        <div class="form-group col-md-2">
                <label for="{{form.postal_code.name}}">{{form.postal_code.label}}</label>
                {{form.postal_code|add_class:'form-control'}}
                {{form.non_field_errors}}
        </div>
        </div>
        <div class="form-row">
                <div class="form-group col-md-6">
                <label for="{{form.phone_number.name}}">{{form.phone_number.label}}</label>
                {{form.phone_number|add_class:'form-control'}}
                {{form.non_field_errors}}
                </div>
                <div class="form-group col-md-6">
                <label for="{{form.comment.name}}">{{form.comment.label}}</label>
                {{form.comment|add_class:'form-control'|attr:"placeholder:Additional Comments"}}
                {{form.non_field_errors}}
                </div>
            </div>
        <button type="submit" class="btn btn-primary">Place order</button>    
    </form>
</div>
{% endblock %}

orders/templates/orders/order/created.html
{% extends "catalog/home.html" %}

{% block content %}
<div class="col-lg-9">
    <h1>Thank you</h1>
        <p>Your order has been successfully completed. Your order number is
    <strong>{{ order.id }}</strong>.</p>
</div>
{% endblock %}

orders/templates/orders/order/user_orders.html
{% extends "catalog/home.html" %}

{% block content %}
<div class="col-lg-9">

    <h1>Your orders</h1>
    {% for order in user_order %}
        <li>{{order}}</li>
    {% endfor %}

    {% for book in user_order.orderbook_set.all %}
        {{book}}
    {% endfor %}

</div>
{% endblock %}