cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:book_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:book_id>/', views.cart_remove, name='cart_remove'),
]

catalog/urls.py
from django.urls import path
from catalog import views

app_name = 'catalog'

urlpatterns = [
    path('', views.home, name='home'),
    path('books/', views.books, name='books'),
    path('authors/', views.authors, name='authors'),
    # Lookup by id only, use slug only for SEO/readability
    path('book/<int:pk>', views.book_detail, name='book_detail'),
    path('book/<int:pk>/<slug:slug>', views.book_detail, name='book_detail'),
    path('author/<int:pk>', views.author_detail, name='author_detail'),
    path('author/<int:pk>/<slug:slug>', views.author_detail, name='author_detail')
]

digital_library/urls.py
from django.contrib import admin
from django.urls import path, include
# Develoment only
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('', include('catalog.urls', namespace='catalog')),
    path('orders/', include('orders.urls', namespace='orders'))
]


if settings.DEBUG: # new
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path

from . import views

app_name = 'orders'

urlpatterns = [
    path('create/', views.order_create, name='order_create'),
    path('', views.user_orders, name='user_orders'),
]

catalog/models.py
import uuid
from django.db import models
from django.urls import reverse
from django.template.defaultfilters import slugify


class Book(models.Model):
    """Book."""

    title = models.CharField(max_length=200, blank=False)
    authors = models.ManyToManyField('Author')
    subtitle = models.CharField(max_length=200, blank=True)
    publisher = models.CharField(max_length=100, blank=True)
    description = models.TextField(max_length=1000,                                 
                                   help_text='Enter a brief description of the book')
    published_date = models.DateField(null=True, blank=True)
    # https://en.wikipedia.org/wiki/International_Standard_Book_Number
    isbn = models.CharField('ISBN', max_length=13)
    genre = models.ManyToManyField('Genre', help_text='Choose a book genre')
    pages = models.IntegerField(blank=True, null=True)
    language = models.ForeignKey('Language', on_delete=models.SET_NULL, null=True)
    cover = models.ImageField(upload_to='book_covers/%Y/%m/', default='book_covers/None/no-img.jpg',
                              blank=True)
    slug = models.SlugField(help_text='A slug is a short label, used in URLs')
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    
    def display_genre(self):
        """Creates a string for the Genre. This is required to display genre in Admin."""
        return ', '.join([genre.category for genre in self.genre.all()])

    display_genre.short_description = 'Genre'

    def display_authors(self):
        return ', '.join(author.last_name for author in self.authors.all())

    display_genre.short_description = 'Authors'

    def get_absolute_url(self):
        return reverse('catalog:book_detail', args=[str(self.id), self.slug])

    def __str__(self):
        return self.title


class Author(models.Model):
    """Model representing a book author."""
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    date_of_birth = models.DateField(null=True, blank=True)
    date_of_death = models.DateField('Died', null=True, blank=True)
    slug = models.SlugField(blank=False, null=True,
                            help_text='A slug is a short label, used in URLs')

    # Overide a save method to update slug for all future records
    # def save(self, *args, **kwargs):
    #     self.slug = slugify(self.first_name, self.last_name)
    #     super(Author, self).save(*args, **kwargs)
    # To generate a slug in existing table
    # >>> from django.template.defaultfilters import slugify
    # >>> for obj in MyModel.objects.all():
    # ...     obj.slug = slugify(obj.title)
    # ...     obj.save()

    class Meta:
        ordering = ['last_name', 'first_name']

    def get_absolute_url(self):
        return reverse('catalog:author_detail', args=[str(self.id), self.slug])

    def __str__(self):
        return f'{self.first_name} {self.last_name}'

#class Isbn(model.Model):
class Genre(models.Model):
    """Model representing a book genre."""
    category = models.CharField(max_length=200, help_text='Enter a book genre')
    slug = models.SlugField(max_length=200, help_text='A slug is a short label, used in URLs')
    
    class Meta:
        ordering = ['category']

    def __str__(self):
        return self.category


class BookInstance(models.Model):
    """Model representing a specific copy of a book."""
    id = models.UUIDField(primary_key=True, default=uuid.uuid4,
                          help_text='Unique ID for this particular book across whole store')
    book = models.ForeignKey('Book', on_delete=models.SET_NULL, null=True)
    imprint = models.CharField(max_length=200)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    stock = models.PositiveIntegerField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    
    AVAILABILITY_STATUS = (
        ('u', 'Unavailable'),
        ('c', 'Coming soon'),
        ('a', 'Available'),
        ('s', 'Sold out'),
    )

    status = models.CharField(
        max_length=1,
        choices=AVAILABILITY_STATUS,
        blank=True,
        default='u',
        help_text='Book availability',
    )

    class Meta:
        ordering = ['book']

    def __str__(self):
        """String for representing the Model object."""
        return f'{self.id} ({self.book.title})'

class Language(models.Model):
    """Model representing a Language (e.g. English, French, Japanese, etc.)"""
    name = models.CharField(max_length=200,
                            help_text="Enter the book's natural language (e.g. English, French, Japanese etc.)")

    def __str__(self):
        """String for representing the Model object (in Admin site etc.)"""
        return self.name

catalog/views.py
import re
from datetime import datetime
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.shortcuts import render
from django.shortcuts import get_object_or_404

from catalog.models import Book, Author, BookInstance, Genre, Language
from cart.forms import CartAddProductForm

def home(request):
    """View function for home page of site."""

    # Generate counts of some of the main objects
    num_books = Book.objects.all().count()
    num_instances = BookInstance.objects.all().count()
    
    # Available books (status = 'a')
    num_instances_available = BookInstance.objects.filter(status__exact='a').count()
    
    # The 'all()' is implied by default
    num_authors = Author.objects.count()

    # Get latest published books
    latest_books = Book.objects.all()[:6]
    
    context = {
        'num_books': num_books,
        'num_instances': num_instances,
        'num_instances_available': num_instances_available,
        'num_authors': num_authors,
        'latest_books': latest_books,
    }

    # Render the HTML template index.html with the data in the context variable
    return render(request, 'catalog/home.html', context=context)

def books(request):
    """Return the list of all books."""

    # Get list of all books
    book_list = Book.objects.all()
    return render(
        request,
        'catalog/book_list.html',
        {
            'book_list': book_list,
        }
    )

def book_detail(request, pk, slug=None):
    """View function for details of the specific book."""
    book = get_object_or_404(Book, pk=pk)
    # if slug in url is not correct let Django
    # calculate the canonical URL for an object
    if slug != book.slug:
        return redirect(book.get_absolute_url())

    cart_product_form = CartAddProductForm()
    return render(
        request,
        'catalog/book_detail.html',
        {
            'book': book,
            'cart_product_form':cart_product_form,
        }
    )

def authors(request):
    """Return the list of all authors."""

    author_list = Author.objects.all()
    return render(
        request,
        'catalog/author_list.html',
        {
            'author_list': author_list,
        }
    )


def author_detail(request, pk, slug=None):
    """View function for author details."""

    author = get_object_or_404(Author, pk=pk)
    author_books = author.book_set.all()
    
    # if slug in url is not correct let Django
    # calculate the canonical URL for an object
    if slug != author.slug:
        return redirect(author.get_absolute_url())
    return render(
        request,
        'catalog/author_detail.html',
        {
            'author': author,
            'author_books': author_books,
        }
    )

catalog/templates/catalog/author_detail.html
{% extends "catalog/index.html" %}

{% block content %}
<div class="col-lg-9">
        <div  class="carousel slide my-4"></div>
  <h1>{{ author }}</h1>
  <h3>Books</h3> 
    <ul>
        {% for book in author_books %}
            <li>
                <a href="{{ book.get_absolute_url }}"><strong>{{ book }}</strong></a>
                <p>{{ book.description|truncatewords:70 }}</p>
            </li>
        {% endfor %}
    </ul>
</div>

{% endblock %}

catalog/templates/catalog/author_list.html
{% extends "catalog/home.html" %}

{% block content %}
<div class="col-lg-9">
    <div id="carouselExampleIndicators" class="carousel slide my-4" data-ride="carousel">
    </div>  
        <h1>Authors</h1>    
        {% for author in author_list %}
          <li>
            <a href="{{ author.get_absolute_url }}">{{author}}</a>
          </li>
        {% endfor %}     
</div>
  <!-- /.col-lg-9 -->

{% endblock %}

catalog/templates/catalog/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  {% block title %}<title>Local Library</title>{% endblock %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  <!-- Add additional CSS in static file -->
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>
  <div class="container-fluid">
    <div class="row">
      <div class="col-sm-2">
      {% block sidebar %}
        <ul class="sidebar-nav">
          <li><a href="{% url 'catalog:home' %}">Home</a></li>
          <li><a href="{% url 'catalog:books' %}">All books</a></li>
          <li><a href="{% url 'catalog:authors' %}">All authors</a></li>
        </ul>
     {% endblock %}
      </div>
      <div class="col-sm-10 ">{% block content %}{% endblock %}</div>
    </div>
  </div>
</body>
</html>

catalog/templates/catalog/book_detail.html
{% extends "catalog/home.html" %}

{% block content %}
<div class="col-lg-9">
    <div  class="carousel slide my-4"></div>
  <img height="47%" width="47%" src="{{ book.cover.url }}" alt="img">
  
  <h1>Title: {{ book.title }}</h1>
  <p><strong>Subtitle:</strong> {{ book.subtitle }}</p>  
  <p><strong>Author:</strong> {% for author in book.authors.all %}<a href="{{ author.get_absolute_url }}">{{ author }}{% if not forloop.last %}, {% endif %}{% endfor %}</a></p> <!-- author detail link not yet defined -->
  
  <p><strong>Summary:</strong> {{ book.publisher }}</p>
  <p><strong>ISBN:</strong> {{ book.isbn }}</p> 
  <p><strong>Language:</strong> {{ book.language }}</p>  
  <p><strong>Genre:</strong> {% for genre in book.genre.all %} {{ genre }}{% if not forloop.last %}, {% endif %}{% endfor %}</p>  
  <p><strong>Description:</strong><p></p>{{ book.description }}</p>
  <div style="margin-left:20px;margin-top:20px">

    {% for book_instance in book.bookinstance_set.all %}
      <hr>
      <p class="{% if copy.status == 'a' %}text-success{% elif copy.status == 'm' %}text-danger{% else %}text-warning{% endif %}">{{ copy.get_status_display }}</p>
      {% if copy.status != 'a' %}
      <p><strong>{{copy.status}}</strong></p>
        <p><strong>Price:</strong> {{book_instance.price}} USD</p>
      {% endif %}
      <p class="price">${{ book_instance.price }}</p>
      <form action="{% url "cart:cart_add" book_instance.book.id %}" method="post">
      {{ cart_product_form }}
      {% csrf_token %}
      <input type="submit" value="Add to cart">
      </form>

    {% endfor %}
  </div>
</div>
{% endblock %}

catalog/templates/catalog/book_list.html
{% extends "catalog/home.html" %}
{% load sidebar_tags %}
{% block content %}

      <div class="col-lg-9">

        <div id="carouselExampleIndicators" class="carousel slide my-4" data-ride="carousel">

        </div>

        <div class="row">
          {% for book in book_list %}
          <div class="col-lg-4 col-md-6 mb-4">
            <div class="card h-100">
              <a href="{{book.get_absolute_url}}"><img class="card-img-top" src="{{ book.cover.url }}" alt=""></a>
              <div class="card-body">
                <h4 class="card-title">
                  <a href="{{book.get_absolute_url}}">{{ book.title }}</a>
                </h4>
                {% for book_instance in book.bookinstance_set.all %}
                <h5>${{ book_instance.price}}</h5>
                {% endfor %}
                <p class="card-text">{{book.description|truncatewords:10}}</p>
              </div>
              <div class="card-footer">
                <small class="text-muted">&#9733; &#9733; &#9733; &#9733; &#9734;</small>
              </div>
            </div>
          </div>
          {% endfor %}
        </div>
        <!-- /.row -->

      </div>
      <!-- /.col-lg-9 -->

  </div>
{% endblock %}

catalog/templates/catalog/footer.html
<footer class="footer">
  <div class="container">
    <div class="row row-grid align-items-center mb-5">
      <div class="col-lg-6">
        <h3 class="text-primary font-weight-light mb-2">Thank you for supporting us!</h3>
        <h4 class="mb-0 font-weight-light">Let's get in touch on any of these platforms.</h4>
      </div>
      <div class="col-lg-6 text-lg-center btn-wrapper">
        <a target="_blank" href="#" class="btn btn-neutral btn-icon-only btn-twitter btn-round btn-lg" data-toggle="tooltip" data-original-title="Follow us">
          <i class="fab fa-twitter"></i>
        </a>
        <a target="_blank" href="#" class="btn btn-neutral btn-icon-only btn-facebook btn-round btn-lg" data-toggle="tooltip" data-original-title="Like us">
          <i class="fab fa-facebook-square"></i>
        </a>
        <a target="_blank" href="https://github.com/casol" class="btn btn-neutral btn-icon-only btn-github btn-round btn-lg" data-toggle="tooltip" data-original-title="Star on Github">
          <i class="fab fa-github"></i>
        </a>
      </div>
    </div>
    <hr>
    <div class="row align-items-center justify-content-md-between">
      <div class="col-md-6">
        <div class="copyright">
          &copy; 2019 <a href="https://github.com/casol/Digital-Library" target="_blank">Digital BookStore</a>.
        </div>
      </div>
      <div class="col-md-6">
        <ul class="nav nav-footer justify-content-end">
          <li class="nav-item">
            <a href="https://github.com/casol" class="nav-link" target="_blank">Casol</a>
          </li>
          <li class="nav-item">
            <a href="https://github.com/casol" class="nav-link" target="_blank">About Us</a>
          </li>
          <li class="nav-item">
            <a href="https://frombitstobytes.com/" class="nav-link" target="_blank">Blog</a>
          </li>
          <li class="nav-item">
            <a href="https://github.com/creativetimofficial/argon-design-system/blob/master/LICENSE.md" class="nav-link" target="_blank">MIT License</a>
          </li>
        </ul>
      </div>
    </div>
  </div>
</footer>

catalog/templates/catalog/home.html
{% extends "catalog/index.html" %}
{% load sidebar_tags %}
{% block content %}
  <!-- Page Content --> 
   
      <div class="col-lg-9">
        <div id="carouselExampleIndicators" class="carousel slide my-4" data-ride="carousel">
          <ol class="carousel-indicators">
            <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
            <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
            <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
          </ol>
          <div class="carousel-inner" role="listbox">
            <div class="carousel-item active">
              <img class="d-block img-fluid" src="http://placehold.it/900x350" alt="First slide">
            </div>
            <div class="carousel-item">
              <img class="d-block img-fluid" src="http://placehold.it/900x350" alt="Second slide">
            </div>
            <div class="carousel-item">
              <img class="d-block img-fluid" src="http://placehold.it/900x350" alt="Third slide">
            </div>
          </div>
          <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
          </a>
          <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
          </a>
        </div>

        <div class="row">
          {% for book in latest_books %}
          <div class="col-lg-4 col-md-6 mb-4">
            <div class="card h-100">
              <a href="{{book.get_absolute_url}}"><img class="card-img-top" src="{{ book.cover.url }}" alt=""></a>
              <div class="card-body">
                <h4 class="card-title">
                  <a href="{{book.get_absolute_url}}">{{ book.title }}</a>
                </h4>
                {% for book_instance in book.bookinstance_set.all %}
                <h5>${{ book_instance.price}}</h5>
                {% endfor %}
                <p class="card-text">{{book.description|truncatewords:10}}</p>
              </div>
              <div class="card-footer">
                <small class="text-muted">&#9733; &#9733; &#9733; &#9733; &#9734;</small>
              </div>
            </div>
          </div>
          {% endfor %}
        </div>
        <!-- /.row -->

      </div>
      <!-- /.col-lg-9 -->

{% endblock content %}

catalog/templates/catalog/index.html
{% load sidebar_tags %}
<!DOCTYPE html>
<html lang="en">
{% block head %}
  {% block meta %}
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="Start your development with a Design System for Bootstrap 4.">
  <meta name="author" content="Creative Tim">
  {% endblock meta %}
  <title>{% block title %}Digital Library{% endblock %}</title>
  {% block stylesheets %}
  
  <!-- Favicon -->
  <link href="/static/img/brand/icons8-books-96.png" rel="icon" type="image/png">
  <!-- Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700" rel="stylesheet">
  <!-- Icons -->
  <link href="/static/vendor/nucleo/css/nucleo.css" rel="stylesheet">
  <script src="https://kit.fontawesome.com/2c770c206d.js" crossorigin="anonymous"></script>
  
  {% endblock stylesheets %}
  <!-- Argon CSS -->
  <link type="text/css" href="/statifc/css/argon.css" rel="stylesheet">

  <!-- Bootstrap core CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <!-- Custom styles for this template -->
  <link href="/static/css/shop-homepage.css" rel="stylesheet">

{% endblock head %}  
</head>

<body>
  {% block body %}
  {% block top_navigation %}
    
    {% include "catalog/top_navigation.html" %}

  {% endblock top_navigation %}
  
  <div class="container"> 
      <div class="row">
          {% block sidebar %}          
              {% sidebar %}
          {% endblock %}
              {% block content %}
              
                <!-- {{ content }} -->

              {% endblock content %}
        </div>
  </div>

  {% block footer %}

    {% include "catalog/footer.html" %}
 
  {% endblock footer %}

  {% block javascript %}

  <!-- Core -->
    <!-- Bootstrap core JavaScript -->   

  
  <script src="/static/vendor/jquery/jquery.min.js"></script>
  <script src="/static/vendor/popper/popper.min.js"></script>
  <script src="/static/vendor/bootstrap/bootstrap.min.js"></script>
  <script src="/static/vendor/headroom/headroom.min.js"></script>
  <!-- Optional JS -->
  <script src="/static/vendor/onscreen/onscreen.min.js"></script>
  <script src="/static/vendor/nouislider/js/nouislider.min.js"></script>
  <script src="/static/vendor/bootstrap-datepicker/js/bootstrap-datepicker.min.js"></script>
  <!-- Argon JS -->
  <script src="/static/js/argon.js?v=1.1.0"></script>
  {% endblock %}
{% endblock body %}
</body>

</html>

catalog/templates/catalog/landing.html
<!DOCTYPE html>
<html lang="en">
  {% block head %}
    {% block meta %}
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="Start your development with a Design System for Bootstrap 4.">
  <meta name="author" content="Creative Tim">
    {% endblock meta %}
  <title>Digital Library</title>
  {% block stylesheets %}
  <!-- Favicon -->
  <link href="/static/img/brand/favicon.png" rel="icon" type="image/png">
  <!-- Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700" rel="stylesheet">
  <!-- Icons -->
  <link href="/static/vendor/nucleo/css/nucleo.css" rel="stylesheet">
  <link href="/static/vendor/font-awesome/css/font-awesome.min.css" rel="stylesheet">
  {% endblock stylesheets %}
  <!-- Argon CSS -->
  <link type="text/css" href="/static/css/argon.css?v=1.1.0" rel="stylesheet">
  {% endblock head %}
</head>

<body>
  {% block body %}

    {% block top_navigation %}

      {% include "catalog/top_navigation.html" %}

    {% endblock top_navigation %}

    {% block content %}

      <!-- {{ content }} -->

    {% endblock content %}
  
  {% block footer %}

  {% include "catalog/footer.html" %}

  {% endblock footer %}
  {% block javascript %}
  <!-- Core -->
  <script src="/static/vendor/jquery/jquery.min.js"></script>
  <script src="/static/vendor/popper/popper.min.js"></script>
  <script src="/static/vendor/bootstrap/bootstrap.min.js"></script>
  <script src="/static/vendor/headroom/headroom.min.js"></script>
  <!-- Argon JS -->
  <script src="/static/js/argon.js?v=1.1.0"></script>
  {% endblock %}
{% endblock body %}
</body>

</html>

catalog/templates/catalog/sidebar.html
<div class="col-lg-3">

    <h1 class="my-4"></h1>        
        <div id="accordion">
            <div class="card">
            <div class="card-header" id="headingOne">
                <h5 class="mb-0">
                <button class="btn btn-link" data-toggle="collapse" data-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">               <i class="fa" aria-hidden="true"></i>
                    Books
                </button>
                </h5>
            </div>
        
            <div id="collapseOne" class="collapse show" aria-labelledby="headingOne" data-parent="#accordion">
                    <div class="list-group">
                        {% for genre in genres %}
                        <a href="#" class="list-group-item list-group-item-action">{{genre}}</a>   
                        {% endfor %}                     
                    </div>
            </div>
            </div>
            <div class="card">
            <div class="card-header" id="headingTwo">
                <h5 class="mb-0">
                <button class="btn btn-link collapsed" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
                    <i class="fa" aria-hidden="true"></i>
                    Popular in Books
                </button>
                </h5>
            </div>
            <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordion">
                <div class="card-body">
                Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod. Brunch 3 wolf moon tempor, sunt aliqua put a bird on it squid single-origin coffee nulla assumenda shoreditch et. Nihil anim keffiyeh helvetica, craft beer labore wes anderson cred nesciunt sapiente ea proident. Ad vegan excepteur butcher vice lomo. Leggings occaecat craft beer farm-to-table, raw denim aesthetic synth nesciunt you probably haven't heard of them accusamus labore sustainable VHS.
                </div>
            </div>
            </div>
            <div class="card">
            <div class="card-header" id="headingThree">
                <h5 class="mb-0">
                <button class="btn btn-link collapsed" data-toggle="collapse" data-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
                    <i class="fa" aria-hidden="true"></i>
                    Author
                </button>
                </h5>
            </div>
            <div id="collapseThree" class="collapse" aria-labelledby="headingThree" data-parent="#accordion">
                <div class="list-group">
                    {% for author in authors %}
                    <a href="{{ author.get_absolute_url }}" class="list-group-item list-group-item-action">{{author}}</a>   
                    {% endfor %}                     
                </div>
            </div>
            </div>
        </div>        
        
</div>
    <!-- /.col-lg-3 -->
    

catalog/templates/catalog/top_navigation.html
  <!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
      <a class="navbar-brand" href="{% url "catalog:home"  %}">Digital BookStore</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item active">
            <a class="nav-link" href="#">Home
              <span class="sr-only">(current)</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">About</a>
          </li>
          {% with total_items=cart|length %}
          <li class="nav-item">
            <a href="{% url "cart:cart_detail" %}"><span class="fa-stack fa-1x has-badge" data-count="{{ total_items }}">
              <i class="fa fa-circle fa-stack-2x"></i>
              <i class="fa fa-shopping-cart fa-stack-1x fa-inverse"></i>             
            </span></a>
          </li>          
          {% endwith %}

          <li class="nav-item dropdown">
            <a href="#" class="nav-link" data-toggle="dropdown" role="button">
              <i class="ni ni-collection d-lg-none"></i>
              <span class="nav-link-inner--text">{{ user.email }}</span>
            </a>
            <div class="dropdown-menu">              
              <a href="../examples/profile.html" class="dropdown-item">Your Profile</a>
              <a href="{% url 'orders:user_orders' %}" class="dropdown-item">Your Orders</a>
              <a href="{% url 'account_logout' %}" class="dropdown-item">Log Out</a>
            </div>
          </li> 

          {% if user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'account_logout' %}"><i class="fas fa-sign-out-alt"></i> Log Out</a>
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'account_login' %}"><span class="fas fa-sign-in-alt"></span> Log In</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'account_signup' %}"><span class="fas fa-user"></span> Sign Up</a>
          </li>
          {% endif %}
        </ul>
      </div>
    </div>
  </nav>  